// This file is auto-generated by @hey-api/openapi-ts

export type { AgentChatRequestModel, AgentChatResponseModel, ChatMessageDto, ChatRequest, ClientOptions, GetWeatherForecastData, GetWeatherForecastResponse, GetWeatherForecastResponses, PostApiAgentByConversationIdData, PostApiAgentByConversationIdResponse, PostApiAgentByConversationIdResponses, PostApiChatData, PostApiChatResponses, PostApiChatStreamData, PostApiChatStreamResponses, WeatherForecast } from './types.gen';
