// This file is auto-generated by @hey-api/openapi-ts

export type { ChatMessageDto, ChatRequest, ClientOptions, GetWeatherForecastData, GetWeatherForecastResponse, GetWeatherForecastResponses, PostApiChatData, PostApiChatResponses, PostApiChatStreamData, PostApiChatStreamResponses, WeatherForecast } from './types.gen';
