// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:5241/' | (string & {});
};

export type ChatMessageDto = {
    role: string;
    content: string;
};

export type ChatRequest = {
    messages: Array<ChatMessageDto>;
};

export type WeatherForecast = {
    date?: string;
    temperatureC?: number;
    temperatureF?: number;
    summary?: string | null;
};

export type PostApiChatData = {
    body: ChatRequest;
    path?: never;
    query?: never;
    url: '/api/chat';
};

export type PostApiChatResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiChatStreamData = {
    body: ChatRequest;
    path?: never;
    query?: never;
    url: '/api/chat/stream';
};

export type PostApiChatStreamResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetWeatherForecastData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/WeatherForecast';
};

export type GetWeatherForecastResponses = {
    /**
     * OK
     */
    200: Array<WeatherForecast>;
};

export type GetWeatherForecastResponse = GetWeatherForecastResponses[keyof GetWeatherForecastResponses];
